// Basic translations (replace with more accurate ones if needed)
const translations = {
    en: {
        pageTitle: "Ali Ashraf Elkhosht - Professional Profile",
        profileName: "Ali Ashraf Elkhosht",
        profileSubtitle: "IT Manager | Odoo Implementer | FrontEnd Developer",
        contactTitle: "Contact",
        emailLabel: "Email:",
        linkedinLabel: "LinkedIn:",
        summaryTitle: "Summary",
        summaryText: "Ali Ashraf Elkhosht is an IT professional with over three years of experience, demonstrating a strong commitment to excellence in technology services. His career progression shows a transition from IT Specialist roles to his current position as an IT Manager. He emphasizes leveraging his skills in IT management and proficiency with tools like Microsoft Office to enhance technology infrastructure. Ali is dedicated to delivering robust and reliable IT solutions, aligning his competencies with organizational vision, and fostering an environment of innovation and continuous improvement. His approach values forward-thinking and strategic technology advancement.",
        experienceTitle: "Experience",
        exp1Title: "IT Manager",
        exp1Company: "Bin Shujaa Co.",
        exp1Location: "Riyadh, Saudi Arabia",
        exp1DurationLabel: "Duration:",
        exp1Duration: "October 2024 – Present (7 months as of April 2025)",
        exp1SkillsLabel: "Key Skills Mentioned:",
        exp1Skills: "Odoo implementation, Systems Analysis.",
        exp2Title: "Senior Information Technology Engineer",
        exp2Company: "Yama Engineering Systems",
        exp2Location: "Cairo, Egypt",
        exp2DurationLabel: "Duration:",
        exp2Duration: "May 2022 – Present (3 years as of April 2025)",
        exp2SkillsLabel: "Key Skills Mentioned:",
        exp2Skills: "Linux System Administration, Object-Oriented Programming (OOP).",
        exp3Title: "IT Specialist",
        exp3Company: "Safeco Group",
        exp3Location: "Cairo, Egypt",
        exp3DurationLabel: "Duration:",
        exp3Duration: "May 2021 – May 2022 (1 year 1 month)",
        exp3SkillsLabel: "Key Skills Mentioned:",
        exp3Skills: "IT Management, Technology Services.",
        exp4Title: "Full Stack Developer",
        exp4Company: "Information Technology Institute (ITI)",
        exp4Location: "Remote - Beni Suef, Egypt",
        exp4DurationLabel: "Duration:",
        exp4Duration: "September 2020 – January 2021 (5 months)",
        exp4SkillsLabel: "Key Skills Mentioned:",
        exp4Skills: "Full-Stack Development, Dotnet.",
        educationTitle: "Education",
        edu1School: "Information Technology Institute (ITI)",
        edu1DegreeLabel: "Degree:",
        edu1Degree: "Bachelor's degree, Computer Software Engineering",
        edu1DurationLabel: "Duration:",
        edu1Duration: "September 2020 – January 2021",
        edu1GradeLabel: "Grade:",
        edu1Grade: "Excellent",
        edu1FocusLabel: "Focus:",
        edu1Focus: ".Net Full Stack web development",
        edu1SkillsLabel: "Key Skills Mentioned:",
        edu1Skills: "AngularJS, C#.",
        edu2School: "El Shorouk Academy",
        edu2Location: "Egypt",
        edu2DegreeLabel: "Degree:",
        edu2Degree: "Bachelor's degree, Computer Science",
        edu2DurationLabel: "Duration:",
        edu2Duration: "September 2014 – June 2018 (3 years 10 months)",
        skillsTitle: "Skills",
        skillsIntro: "Ali possesses a diverse skill set spanning IT management, systems analysis, software development, and specific technologies. Key areas include:",
        skillsCat1: "IT Management & Operations:",
        skillsList1: "IT Management, Technology Services, Project Management, Linux System Administration.",
        skillsCat2: "ERP & Business Systems:",
        skillsList2: "Odoo implementation, Systems Analysis, Business Systems Analysis, Software System Analysis.",
        skillsCat3: "Software Development:",
        skillsList3: "Full-Stack Development, Object-Oriented Programming (OOP).",
        skillsCat4: "Microsoft Technologies:",
        skillsList4: ".NET Framework (ASP.NET, ASP.NET MVC, ASP.NET Core, .NET Core), C#.",
        skillsCat5: "Web Technologies:",
        skillsList5: "REST APIs, ASP.NET Web API, AngularJS, Postman API, WordPress.",
        skillsCat6: "Operating Systems:",
        skillsList6: "Microsoft Windows, MacOS, Ubuntu.",
        noteText: "(Note: This summary is based on information from LinkedIn profile screenshots and PDF provided by Ali Ashraf Elkhosht.)",
        footerText: "Generated by Manus AI",
        switchLangButton: "العربية"
    },
    ar: {
        pageTitle: "علي أشرف الخشت - الملف الشخصي المهني",
        profileName: "علي أشرف الخشت",
        profileSubtitle: "مدير تقنية المعلومات | منفذ Odoo | مطور واجهات أمامية",
        contactTitle: "الاتصال",
        emailLabel: "البريد الإلكتروني:",
        linkedinLabel: "لينكدإن:",
        summaryTitle: "الملخص",
        summaryText: "علي أشرف الخشت هو محترف في مجال تكنولوجيا المعلومات يتمتع بخبرة تزيد عن ثلاث سنوات، ويظهر التزامًا قويًا بالتميز في خدمات التكنولوجيا. يُظهر تطوره الوظيفي انتقالًا من أدوار أخصائي تكنولوجيا المعلومات إلى منصبه الحالي كمدير لتكنولوجيا المعلومات. يؤكد على الاستفادة من مهاراته في إدارة تكنولوجيا المعلومات وإتقانه لأدوات مثل Microsoft Office لتعزيز البنية التحتية التكنولوجية. يكرس علي جهوده لتقديم حلول تكنولوجيا معلومات قوية وموثوقة، ومواءمة كفاءاته مع رؤية المؤسسة، وتعزيز بيئة الابتكار والتحسين المستمر. يقدر نهجه التفكير المستقبلي والتقدم التكنولوجي الاستراتيجي.",
        experienceTitle: "الخبرة",
        exp1Title: "مدير تقنية المعلومات",
        exp1Company: "شركة بن شجاع", // Assuming translation
        exp1Location: "الرياض، المملكة العربية السعودية",
        exp1DurationLabel: "المدة:",
        exp1Duration: "أكتوبر 2024 – الحاضر (7 أشهر حتى أبريل 2025)",
        exp1SkillsLabel: "المهارات الرئيسية المذكورة:",
        exp1Skills: "تنفيذ Odoo، تحليل النظم.",
        exp2Title: "مهندس تقنية معلومات أول",
        exp2Company: "Yama Engineering Systems",
        exp2Location: "القاهرة، مصر",
        exp2DurationLabel: "المدة:",
        exp2Duration: "مايو 2022 – الحاضر (3 سنوات حتى أبريل 2025)",
        exp2SkillsLabel: "المهارات الرئيسية المذكورة:",
        exp2Skills: "إدارة نظام لينكس، البرمجة الشيئية (OOP).",
        exp3Title: "أخصائي تقنية معلومات",
        exp3Company: "Safeco Group",
        exp3Location: "القاهرة، مصر",
        exp3DurationLabel: "المدة:",
        exp3Duration: "مايو 2021 – مايو 2022 (سنة وشهر واحد)",
        exp3SkillsLabel: "المهارات الرئيسية المذكورة:",
        exp3Skills: "إدارة تقنية المعلومات، خدمات التكنولوجيا.",
        exp4Title: "مطور متكامل",
        exp4Company: "معهد تكنولوجيا المعلومات (ITI)",
        exp4Location: "عن بعد - بني سويف، مصر",
        exp4DurationLabel: "المدة:",
        exp4Duration: "سبتمبر 2020 – يناير 2021 (5 أشهر)",
        exp4SkillsLabel: "المهارات الرئيسية المذكورة:",
        exp4Skills: "تطوير متكامل، Dotnet.",
        educationTitle: "التعليم",
        edu1School: "معهد تكنولوجيا المعلومات (ITI)",
        edu1DegreeLabel: "الدرجة العلمية:",
        edu1Degree: "درجة البكالوريوس، هندسة برمجيات الحاسوب",
        edu1DurationLabel: "المدة:",
        edu1Duration: "سبتمبر 2020 – يناير 2021",
        edu1GradeLabel: "التقدير:",
        edu1Grade: "ممتاز",
        edu1FocusLabel: "التركيز:",
        edu1Focus: "تطوير الويب المتكامل باستخدام .Net",
        edu1SkillsLabel: "المهارات الرئيسية المذكورة:",
        edu1Skills: "AngularJS, C#.",
        edu2School: "أكاديمية الشروق",
        edu2Location: "مصر",
        edu2DegreeLabel: "الدرجة العلمية:",
        edu2Degree: "درجة البكالوريوس، علوم الحاسوب",
        edu2DurationLabel: "المدة:",
        edu2Duration: "سبتمبر 2014 – يونيو 2018 (3 سنوات و 10 أشهر)",
        skillsTitle: "المهارات",
        skillsIntro: "يمتلك علي مجموعة متنوعة من المهارات تشمل إدارة تكنولوجيا المعلومات، وتحليل النظم، وتطوير البرمجيات، وتقنيات محددة. تشمل المجالات الرئيسية:",
        skillsCat1: "إدارة وعمليات تقنية المعلومات:",
        skillsList1: "إدارة تقنية المعلومات، خدمات التكنولوجيا، إدارة المشاريع، إدارة نظام لينكس.",
        skillsCat2: "أنظمة تخطيط موارد المؤسسات وأنظمة الأعمال:",
        skillsList2: "تنفيذ Odoo، تحليل النظم، تحليل نظم الأعمال، تحليل نظم البرمجيات.",
        skillsCat3: "تطوير البرمجيات:",
        skillsList3: "تطوير متكامل، البرمجة الشيئية (OOP).",
        skillsCat4: "تقنيات مايكروسوفت:",
        skillsList4: ".NET Framework (ASP.NET, ASP.NET MVC, ASP.NET Core, .NET Core), C#.",
        skillsCat5: "تقنيات الويب:",
        skillsList5: "REST APIs, ASP.NET Web API, AngularJS, Postman API, WordPress.",
        skillsCat6: "أنظمة التشغيل:",
        skillsList6: "Microsoft Windows, MacOS, Ubuntu.",
        footerText: "",
        switchLangButton: "English"
    }
};

document.addEventListener('DOMContentLoaded', () => {
    const langToggleButton = document.getElementById('lang-toggle');
    let currentLang = localStorage.getItem('preferredLang') || 'en'; // Default to English

    function setLanguage(lang) {
        currentLang = lang;
        localStorage.setItem('preferredLang', lang);
        document.documentElement.lang = lang;
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';

        // Update all elements with data-translate attribute
        document.querySelectorAll('[data-translate]').forEach(element => {
            const key = element.getAttribute('data-translate');
            if (translations[lang] && translations[lang][key]) {
                // Handle different element types
                if (element.tagName === 'TITLE') {
                    element.textContent = translations[lang][key];
                } else if (element.tagName === 'P' || element.tagName === 'STRONG' || element.tagName === 'SPAN' || element.tagName === 'H1' || element.tagName === 'H2' || element.tagName === 'EM' || element.tagName === 'BUTTON') {
                    // Direct text content update
                    element.textContent = translations[lang][key];
                } else if (element.tagName === 'A' && key.includes('Label')) {
                     // Special handling for labels before links if needed, or just update text
                     element.textContent = translations[lang][key];
                }
                // Add more conditions here if other tags need special handling (e.g., input placeholders)
            }
        });
        // Update button text
        langToggleButton.textContent = translations[lang].switchLangButton;
    }

    langToggleButton.addEventListener('click', () => {
        const newLang = currentLang === 'en' ? 'ar' : 'en';
        setLanguage(newLang);
    });

    // Set initial language on load
    setLanguage(currentLang);
});

